name: "Sync"

on:
  workflow_dispatch:

jobs:
  sync:
    name: "Get new GitHub release data"
    runs-on: ubuntu-slim
    steps:
      - name: "Check out the GapWWW repository in order to make changes to it"
        uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - name: "Install the required Python modules"
        run: pip3 install PyGithub requests python-dateutil
      - name: "Run the GAP dev release script for updating the website"
        run: python -u etc/update_website.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Show new"
        shell: bash
        run: cat releases.json
